# Generated by Django 5.0.3 on 2024-04-14 14:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mesa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Numero", models.IntegerField()),
                ("Disponible", models.BooleanField(default=True)),
                ("Capacidad", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Mesero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_de_usuario", models.CharField(max_length=50)),
                (
                    "mesa_asignada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meseros",
                        to="Restaurant.mesa",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_de_usuario", models.CharField(max_length=50)),
                ("fecha", models.DateField(default=django.utils.timezone.now)),
                ("hora_inicio", models.TimeField(default=django.utils.timezone.now)),
                (
                    "mesa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservas",
                        to="Restaurant.mesa",
                    ),
                ),
            ],
        ),
    ]
