# Generated by Django 5.0.3 on 2024-04-14 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Restaurant", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mesa",
            old_name="Capacidad",
            new_name="capacidad",
        ),
        migrations.RenameField(
            model_name="mesa",
            old_name="Disponible",
            new_name="disponible",
        ),
        migrations.RenameField(
            model_name="mesa",
            old_name="Numero",
            new_name="numero",
        ),
    ]
