# Generated by Django 5.0.3 on 2024-04-16 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Restaurant", "0003_rename_mesa_asignada_mesero_mesa"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mesero",
            old_name="mesa",
            new_name="mesa_asignada",
        ),
        migrations.RenameField(
            model_name="mesero",
            old_name="nombre_de_usuario",
            new_name="nombre",
        ),
    ]
