# Generated by Django 5.0.3 on 2024-04-18 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Restaurant", "0004_rename_mesa_mesero_mesa_asignada_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="reserva",
            name="nombre_de_usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usuarios",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
