# Generated by Django 5.0.3 on 2024-04-18 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Restaurant", "0005_alter_reserva_nombre_de_usuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reserva",
            name="nombre_de_usuario",
            field=models.CharField(max_length=50),
        ),
    ]
